# CMake generated Testfile for 
# Source directory: /home/weilaidb/git/gtest_eg/gtest-1.7.0
# Build directory: /home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(gtest-death-test_test "gtest-death-test_test")
ADD_TEST(gtest_environment_test "gtest_environment_test")
ADD_TEST(gtest-filepath_test "gtest-filepath_test")
ADD_TEST(gtest-linked_ptr_test "gtest-linked_ptr_test")
ADD_TEST(gtest-listener_test "gtest-listener_test")
ADD_TEST(gtest_main_unittest "gtest_main_unittest")
ADD_TEST(gtest-message_test "gtest-message_test")
ADD_TEST(gtest_no_test_unittest "gtest_no_test_unittest")
ADD_TEST(gtest-options_test "gtest-options_test")
ADD_TEST(gtest-param-test_test "gtest-param-test_test")
ADD_TEST(gtest-port_test "gtest-port_test")
ADD_TEST(gtest_pred_impl_unittest "gtest_pred_impl_unittest")
ADD_TEST(gtest_premature_exit_test "gtest_premature_exit_test")
ADD_TEST(gtest-printers_test "gtest-printers_test")
ADD_TEST(gtest_prod_test "gtest_prod_test")
ADD_TEST(gtest_repeat_test "gtest_repeat_test")
ADD_TEST(gtest_sole_header_test "gtest_sole_header_test")
ADD_TEST(gtest_stress_test "gtest_stress_test")
ADD_TEST(gtest-test-part_test "gtest-test-part_test")
ADD_TEST(gtest_throw_on_failure_ex_test "gtest_throw_on_failure_ex_test")
ADD_TEST(gtest-typed-test_test "gtest-typed-test_test")
ADD_TEST(gtest_unittest "gtest_unittest")
ADD_TEST(gtest-unittest-api_test "gtest-unittest-api_test")
ADD_TEST(gtest-death-test_ex_nocatch_test "gtest-death-test_ex_nocatch_test")
ADD_TEST(gtest-death-test_ex_catch_test "gtest-death-test_ex_catch_test")
ADD_TEST(gtest_no_rtti_unittest "gtest_no_rtti_unittest")
ADD_TEST(gtest-tuple_test "gtest-tuple_test")
ADD_TEST(gtest_use_own_tuple_test "gtest_use_own_tuple_test")
ADD_TEST(gtest_break_on_failure_unittest "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_break_on_failure_unittest.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_catch_exceptions_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_catch_exceptions_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_color_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_color_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_env_var_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_env_var_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_filter_unittest "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_filter_unittest.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_help_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_help_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_list_tests_unittest "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_list_tests_unittest.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_output_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_output_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_shuffle_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_shuffle_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_throw_on_failure_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_throw_on_failure_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_uninitialized_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_uninitialized_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_xml_outfiles_test "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_xml_outfiles_test.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
ADD_TEST(gtest_xml_output_unittest "/usr/local/bin/python" "/home/weilaidb/git/gtest_eg/gtest-1.7.0/test/gtest_xml_output_unittest.py" "--build_dir=/home/weilaidb/git/gtest_eg/gtest-1.7.0/mybuild/${CTEST_CONFIGURATION_TYPE}")
